language: go
go:
  - 1.8.x
install:
  - go get -d -v github.com/Masterminds/glide
  - (cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.12.3 && go install)
  - glide install
script: go test $(go list ./... 2>/dev/null | grep -v /vendor/)
